name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - dotnet-version: '2.1.x'
          tfm: 'netcoreapp2.1'
        - dotnet-version: '3.1.x'
          tfm: 'netcoreapp3.1'
        - dotnet-version: '5.0.x'
          tfm: 'net5.0'
        - dotnet-version: '6.0.x'
          tfm: 'net6.0'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: check directory content
      run: dir
    - name: install dependencies
      run: dotnet restore -p:TargetFramework=${{ matrix.tfm }}
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal -f=${{ matrix.tfm }}
